### ISSUE TITLE
Installing the interachsh-web local

### ISSUE THREAD

**Issue by nitchimon** [projectdiscovery/interactsh-web#41]
Great software!

Are there any prerequisites to install this in a local machine ?

Are there any install/readme for local install ?

I see that there are a few calls to iuenda.com   can this also be brought local to be used instead of calling out to the internet ?

thanks

**Comment by ehsandeep** [comment]
@nitchimon this will be addressed as part of https://github.com/projectdiscovery/interactsh-web/issues/41 with install instruction.
