### ISSUE TITLE
WEB:CORS error

### ISSUE THREAD

**Issue by 1j0ker** [projectdiscovery/interactsh-web#84]
Use "yarn install" to build the web front end and find the error: CORS error：

![image](https://user-images.githubusercontent.com/52748468/164972484-3cbee0b9-b270-4d9a-b6fa-6b4a3535b833.png)

Error reported by the server:

“”“
Failed to compile.

/home/yunwei/interactsh-web-master/src/components/customHost/index.tsx
TypeScript error in /home/yunwei/interactsh-web-master/src/components/customHost/index.tsx(32,5):
Property 'enabled' is missing in type '{ botToken: string; chatId: string; }' but required in type 'Readonly<{ enabled: boolean; botToken: string; chatId: string; }>'.  TS2741

    30 |     tabs: [],
    31 |     token: "",
  > 32 |     telegram: {
       |     ^
    33 |       botToken: '',
    34 |       chatId: '',
    35 |     },
”“”

**Comment by ehsandeep** [comment]
@1j0ker see the notes section for the CORS related error: https://github.com/projectdiscovery/interactsh-web#note

**Comment by ehsandeep** [comment]
Build error should be fixed with latest release - https://github.com/projectdiscovery/interactsh-web/releases/tag/v1.0.1
