### ISSUE TITLE
Custom domain don't work

### ISSUE THREAD

**Issue by phosec** [projectdiscovery/interactsh-web#87]
While setting up a self hosted version of interactsh-web I get this error while registering my custom domain :
```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at CustomHost
```

The POST call to /register is successful tho,

The version hosted at https://app.interactsh.com/ does not work either with my custom domain,

The cli client works fine

Any idea ?

Thanks

**Comment by ScriptSathi** [comment]
Hello, did you set those flag `-acao-url https://app.interactsh.com` for configuring the interactsh server ? From what I've seen, it allows the server to talk with the webui.

**Comment by ehsandeep** [comment]
This is now fixed.
