### ISSUE TITLE
Error occurred when  copy data to clipboard

### ISSUE THREAD

**Issue by testnet0** [projectdiscovery/interactsh-web#92]
When i click copy button,i will see errors:
TypeError: Cannot read properties of undefined (reading 'writeText')
<img width="966" alt="image" src="https://user-images.githubusercontent.com/18673513/191880688-d525af1e-07c4-4d3d-b41e-d3020834dee5.png">

copyDataToClipboard
http://xxxx:3000/static/js/main.chunk.js:6745:57
  6742 | 
  6743 | 
  6744 | 
> 6745 | const copyDataToClipboard = data => navigator.clipboard.writeText(data);
       |                                                         ^  6746 | const generateUrl = (correlationId, incrementNumber, host) => {
  6747 |   const timestamp = Math.floor(Date.now() / 1000);
  6748 |   const increment = incrementNumber;
View source
onClick
http://xxxx:3000/static/js/main.chunk.js:9165:94
  9162 |   lineNumber: 355,
  9163 |   columnNumber: 15
  9164 | }, undefined), /*#__PURE__*/Object(react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_22__["jsxDEV"])(_svgr_webpack_svgo_titleProp_ref_assets_svg_copy_svg__WEBPACK_IMPORTED_MODULE_7__["ReactComponent"], {
> 9165 |   onClick: () => Object(lib__WEBPACK_IMPORTED_MODULE_12__["copyDataToClipboard"])(storedData.selectedTab.url)
       |                                                                                  ^  9166 | }, void 0, false, {
  9167 |   fileName: _jsxFileName,
  9168 |   lineNumber: 358,

**Comment by ehsandeep** [comment]
This should be fixed by now.
